# LLVM Path
LLPATH=/usr

# Compiler
CC=${LLPATH}/clang-10
CXX=${LLPATH}/clang++-10

# Optimization Pass
OPT=opt-10
MY_LLVM_LIB=/HistogramPass/build/Histogram/libLLVMHistogram.so

# Root Path
ROOT=$(realpath ./../..)

# CSV Header
HEADER="id,$(shell cut -d "," -f 1 ${ROOT}/../HistogramPass/opcodes.csv | tail -n +2 | tr "\n" ",")class"